# Generated by Django 4.0.3 on 2022-03-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministracionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_adm', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EngineerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('validated_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EquiposModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_edif', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('equipo_numero', models.IntegerField()),
                ('qr', models.FileField(null=True, upload_to='')),
                ('slug', models.SlugField()),
                ('pagina_numero', models.IntegerField()),
                ('administracion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingenieros.administracionmodel')),
                ('ingeniero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingenieros.engineermodel')),
            ],
        ),
        migrations.CreateModel(
            name='InsepeccionesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('observacion', models.TextField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingenieros.equiposmodel')),
            ],
        ),
    ]
