# Generated by Django 4.0.3 on 2022-03-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equiposmodel',
            name='administracion',
        ),
        migrations.AddField(
            model_name='equiposmodel',
            name='administracion',
            field=models.ManyToManyField(to='ingenieros.administracionmodel'),
        ),
    ]
