# Generated by Django 4.0.3 on 2022-03-26 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieros', '0002_remove_equiposmodel_administracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insepeccionesmodel',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='ingenieros.equiposmodel'),
        ),
    ]
