# Generated by Django 4.0.3 on 2022-04-02 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieros', '0003_alter_insepeccionesmodel_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insepeccionesmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
