# Generated by Django 4.0.3 on 2022-04-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieros', '0004_alter_insepeccionesmodel_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiposmodel',
            name='qr',
            field=models.ImageField(blank=True, upload_to='qrcodes'),
        ),
    ]
