# Generated by Django 4.0.3 on 2022-04-02 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieros', '0005_alter_equiposmodel_qr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsepeccionesModel',
            new_name='InspeccionesModel',
        ),
    ]
