# Generated by Django 4.0.3 on 2022-04-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieros', '0007_alter_equiposmodel_pagina_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiposmodel',
            name='pagina_numero',
            field=models.IntegerField(),
        ),
    ]
