# Generated by Django 4.0.3 on 2022-04-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieros', '0008_alter_equiposmodel_pagina_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiposmodel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
