# Generated by Django 4.0.3 on 2022-04-10 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingenieros', '0009_alter_equiposmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiposmodel',
            name='ingeniero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
