# Generated by Django 4.0.3 on 2022-04-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieros', '0010_alter_equiposmodel_ingeniero'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionesmodel',
            name='pagina_numero',
            field=models.IntegerField(default=11),
        ),
    ]
